controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
<<<<<<< HEAD



app_offre_front:
    path: /FrontAffichageOffre
    controller: App\Controller\OffreController::indexfront
    methods: GET

=======
>>>>>>> 2bd1813 (Add initial set of files)
