controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_reservation_calculate_total:
    path: /reservation/calculate-total
    controller: App\Controller\ReservationController::calculateTotal


app_reservation_search:
    path: /search
    methods: [GET, POST]
    controller: App\Controller\ReservationController::search
